### ISSUE TITLE
Throttle view and dom updates

### ISSUE THREAD

**Issue by copy** [LexiFi/ocaml-vdom#12]
I'm writing an application that receives updates from a server very frequently. These are injected as messages using `Vdom_blit.process`.  I noticed that `Vdom_blit` calls the view function very often, even multiple times per millisecond, I'm guessing after every message, which causes a high cpu usage. Instead, the view function and dom updates should be throttled, preferably using [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) to align with the browser's refresh rate and to avoid input lag.

As a simpler workaround, it would be useful if ocaml-vdom provided a way to send multiple messages at once, so I can queue up external messages and batch-send them myself.

**Comment by alainfrisch** [comment]
Thanks for the suggestion.  Implemented in #14.  Can you confirm that PR/branch improves the situation for your application?

**Comment by copy** [comment]
> Thanks for the suggestion. Implemented in #14. Can you confirm that PR/branch improves the situation for your application?

Yes, this significantly imroves the performance. Thanks for the quick fix!

**Comment by alainfrisch** [comment]
Thanks for the confirmation.  Merged!
