### ISSUE TITLE
switch to dune build?

### ISSUE THREAD

**Issue by joprice** [LexiFi/ocaml-vdom#27]
I tried building this project with nix, and found that while this project doesn't use dune, it's dependency gen_js_api does. I was able to build it by switching from `buildDunePackage` to `stdenv.mkDerivation` and using make and make install for the build and install steps, but it would be nice to have uniformity there, since most opam projects are using dune nowadays. I was going to try to do a pr to add dune but I saw that gen_js_api uses dune, and assumed that this project has a good reason not to use it.

**Comment by alainfrisch** [comment]
No, it's just that we (LexiFi) don't use dune internally yet.  Feel free to contribute a dune file in a PR if you wish.

**Comment by alainfrisch** [comment]
Wish granted!
