### ISSUE TITLE
ocamlbuild plugin

### ISSUE THREAD

**Issue by martindemello** [LexiFi/ocaml-vdom#3]
The js_of_ocaml ocamlbuild plugin doesn't work with ocaml-vdom due to
1. the -no-check-prims flag
2. the use of gen_js_api

It would be very useful to have a fork of the plugin that added the correct flags.

**Comment by alainfrisch** [comment]
Contributions are welcome!  I've never used ocamlbuild, so this is unlikely to happen otherwise.

**Comment by alainfrisch** [comment]
It seems ocamlbuild is loosing mind share in favor of jbuilder/dune these days.  Closing this ticket for now.
